name: ğŸš€ éƒ¨ç½²è‡³è¿œç¨‹æœåŠ¡å™¨ 
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸŸ é…ç½®Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: ğŸ•µï¸â€â™€ï¸ Checkout
        uses: actions/checkout@v2

      - name: ğŸ“¥ å®‰è£…ä¾èµ–
        run: npm install

      - name: ğŸ—ï¸ æ„å»º
        run: npm run build

      - name: ğŸš€ SSHéƒ¨ç½²
        uses: easingthemes/ssh-deploy@v2.2.5
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          remote-username: ${{ secrets.REMOTE_USERNAME }}
          remote-host: ${{ secrets.REMOTE_HOST }}
          local-path: dist/
          remote-path: /www/wwwroot/www.mocd.cc
